-- MySQL Script generated by MySQL Workbench
-- Mon May  3 19:10:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProyectoAdopcionGatos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProyectoAdopcionGatos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoAdopcionGatos` DEFAULT CHARACTER SET utf8 ;
USE `ProyectoAdopcionGatos` ;

-- -----------------------------------------------------
-- Table `ProyectoAdopcionGatos`.`RazasGatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoAdopcionGatos`.`RazasGatos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `ProyectoAdopcionGatos`.`ColoresGatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoAdopcionGatos`.`ColoresGatos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoAdopcionGatos`.`EstadosGato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoAdopcionGatos`.`EstadosGato` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoAdopcionGatos`.`Vacunas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoAdopcionGatos`.`Vacunas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoAdopcionGatos`.`EstadosTramiteAdopcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoAdopcionGatos`.`EstadosTramiteAdopcion` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoAdopcionGatos`.`Gatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoAdopcionGatos`.`Gatos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Edad` INT NOT NULL,
  `Peso` INT NOT NULL,
  `IdRaza` INT NOT NULL,
  `IdColor` INT NOT NULL,
  `IdEstadoGato` INT NOT NULL,
  `PathFotos` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_IdRaza_idx` (`IdRaza` ASC),
  INDEX `fk_IdColor_idx` (`IdColor` ASC),
  INDEX `fk_Gatos_EstadosGato_idx` (`IdEstadoGato` ASC),
  CONSTRAINT `fk_Gatos_RazasGatos`
    FOREIGN KEY (`IdRaza`)
    REFERENCES `ProyectoAdopcionGatos`.`RazasGatos` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gatos_ColoresGatos`
    FOREIGN KEY (`IdColor`)
    REFERENCES `ProyectoAdopcionGatos`.`ColoresGatos` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gatos_EstadosGato`
    FOREIGN KEY (`IdEstadoGato`)
    REFERENCES `ProyectoAdopcionGatos`.`EstadosGato` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoAdopcionGatos`.`TramitesAdopcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoAdopcionGatos`.`TramitesAdopcion` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `NroTramite` VARCHAR(50) NOT NULL,
  `NombrePostulante` VARCHAR(50) NOT NULL,
  `ApellidoPostulante` VARCHAR(50) NOT NULL,
  `IdEstadoTramiteAdopcion` INT NOT NULL,
  `IdGato` INT NOT NULL,
  `FechaEstado` DATETIME NOT NULL,
  `TelefonoPostulante` VARCHAR(50) NOT NULL,
  `Mail` VARCHAR(50) NOT NULL,
  `Direccion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_IdGato_idx` (`IdGato` ASC),
  INDEX `fk_IdEstadoTramiteAdopcion_idx` (`IdEstadoTramiteAdopcion` ASC),
  CONSTRAINT `fk_TramitesAdopcion_Gatos`
    FOREIGN KEY (`IdGato`)
    REFERENCES `ProyectoAdopcionGatos`.`Gatos` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TramitesAdopcion_EstadosTramiteAdopcion`
    FOREIGN KEY (`IdEstadoTramiteAdopcion`)
    REFERENCES `ProyectoAdopcionGatos`.`EstadosTramiteAdopcion` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoAdopcionGatos`.`VacunasxGatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoAdopcionGatos`.`VacunasxGatos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdVacuna` INT NOT NULL,
  `IdGato` INT NOT NULL,
  `Fecha` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_IdVacuna_idx` (`IdVacuna` ASC),
  INDEX `fk_IdGato_idx` (`IdGato` ASC),
  CONSTRAINT `fk_VacunasxGatos_Vacunas`
    FOREIGN KEY (`IdVacuna`)
    REFERENCES `ProyectoAdopcionGatos`.`Vacunas` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VacunasxGatos_Gatos`
    FOREIGN KEY (`IdGato`)
    REFERENCES `ProyectoAdopcionGatos`.`Gatos` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
